service: my-website
provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  stage: dev
plugins:
  - serverless-s3-sync
custom:
  bucketName: mihirogi.org
  s3Sync:
    - bucketName: ${opt:stage}.${self:custom.bucketName}
      localDir: dist/my-website
resources:
  Resources:
    StaticContentsS3:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: Private
        BucketName: ${opt:stage}.${self:custom.bucketName}
        Tags:
          - Key: project
            Value: ${opt:stage}-${self:service}
