# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: . # workspaceのrootパス（絶対パスかworking_directoryからの相対パス）
          paths:
            - . # 共有するパス（絶対パスかrootからの相対パス）
  test:
    docker:
      - image: circleci/node:11-browsers
    working_directory: ~/repo
    steps:
      - attach_workspace: # workspaceをアタッチする
          at: .
      - run:
          name: check format
          command: npm run format:check
      - run:
          name: headless test
          command: npm run test-headless
      - run:
          name: build
          command: npm run build
      - persist_to_workspace:
          root: . # workspaceのrootパス（絶対パスかworking_directoryからの相対パス）
          paths:
            - . # 共有するパス（絶対パスかrootからの相対パス）
  deploy:
    docker:
      - image: circleci/node:11-browsers
    working_directory: ~/repo
    steps:
      - attach_workspace: # workspaceをアタッチする
          at: .
      - run:
          name: Install Serverless CLI
          command: sudo npm i -g serverless
      - run:
          name: create aws credentials
          command: sls config credentials -k ${AWS_ACCESS_KEY} -s ${AWS_SECRET_KEY} -p aws
      - run:
          name: deploy aws
          command: sls deploy --stage prod
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
